public class Address {
    public void homeAddress(){
        string myName = 'Linda Nora';
        System.debug('My name is ' + myName);

        Integer numOfFamilyMembers = 4;
        System.debug('Total number of my family members is: ' + numOfFamilyMembers);

        string myHouseName = 'Home sweet home!';
        System.debug('My house name is ' + myHouseName);

        Integer myHouseNumber = 1100;
        System.debug('My house number is: ' + myHouseNumber);

        String myStreetName = 'Midstream Dr';
        System.debug('My street name is ' + myStreetName);

        String myCity = 'Dallas';
        System.debug('I live in ' + mycity);

        String myState = 'Texas';
        System.debug('My state name is ' + myState);

        String isoCodeState = 'TX';
        System.debug('My state\'s ISO code is ' + isoCodeState);

        String myCountry = 'United States of America';
        System.debug('I live in the ' + myCountry);

        String isoCodeCountry = 'USA';
        System.debug('My country\'s ISO code is ' + isoCodeCountry);

        String myZipCode = '75098';
        System.debug('My zipcode is ' + myZipCode);

        Boolean isCurrentAddress = true;
        System.debug('Is this my current address? ' + isCurrentAddress);
            
    }
}

